// @flow
import type { ERROR_TYPE } from './common';


export type AUTHENTICATION_STARTED_TYPE = {
  type: 'AUTHENTICATION_STARTED',
  payload: {
    username: string,
    password: string,
  },
}
export const AUTHENTICATION_STARTED = 'AUTHENTICATION_STARTED';

export type AUTHENTICATION_COMPLETED_TYPE = {
  type: 'AUTHENTICATION_COMPLETED',
  payload: {
    token: string,
  },
}
export const AUTHENTICATION_COMPLETED = 'AUTHENTICATION_COMPLETED';

export type AUTHENTICATION_FAILED_TYPE = {
  type: 'AUTHENTICATION_FAILED',
  payload: ERROR_TYPE,
}
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';

export type AUTHENTICATION_IDENTITY_CLEARED_TYPE = {
  type: 'AUTHENTICATION_IDENTITY_CLEARED',
}
export const AUTHENTICATION_IDENTITY_CLEARED = 'AUTHENTICATION_IDENTITY_CLEARED';

export type AUTHENTICATION_REFRESH_STARTED_TYPE = {
  type: 'AUTHENTICATION_REFRESH_STARTED',
}
export const AUTHENTICATION_REFRESH_STARTED = 'AUTHENTICATION_REFRESH_STARTED';

export type AUTHENTICATION_REFRESH_COMPLETED_TYPE = {
  type: 'AUTHENTICATION_REFRESH_COMPLETED',
  payload: {
    token: string,
  },
}
export const AUTHENTICATION_REFRESH_COMPLETED = 'AUTHENTICATION_REFRESH_COMPLETED';

export type AUTHENTICATION_REFRESH_FAILED_TYPE = {
  type: 'AUTHENTICATION_REFRESH_FAILED',
  payload: ERROR_TYPE,
}
export const AUTHENTICATION_REFRESH_FAILED = 'AUTHENTICATION_REFRESH_FAILED';


export type AUTHENTICATION_ACTION_TYPE =
  | AUTHENTICATION_STARTED_TYPE
  | AUTHENTICATION_COMPLETED_TYPE
  | AUTHENTICATION_FAILED_TYPE
  | AUTHENTICATION_IDENTITY_CLEARED_TYPE
  | AUTHENTICATION_REFRESH_STARTED_TYPE
  | AUTHENTICATION_REFRESH_COMPLETED_TYPE
  | AUTHENTICATION_REFRESH_FAILED_TYPE;
